name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Execute - Produce actual1.txt output
        run: python main.py > actual1.txt
      
      - name: Test - Compare expected output to acutal output
        run: diff expected.txt actual1.txt

      - name: Execute - Produce actual2.txt output
        run: python main.py > actual2.txt
      
      - name: Test - Compare expected output to acutal output
        run: diff unexpected.txt actual2.txt
